version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    container_name: symfony_php
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: "mysql://root:${MYSQL_ROOT_PASSWORD}@database/symfony"
      MESSENGER_TRANSPORT_DSN: "amqp://guest:guest@rabbitmq:5672/%2f"
    depends_on:
      - database
      - rabbitmq

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mysql:8.0
    container_name: symfony_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: symfony
    volumes:
      - mysql_data:/var/lib/mysql
    secrets:
      - mysql_root_password

  rabbitmq:
    image: rabbitmq:3-management
    container_name: symfony_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mailhog:
    image: mailhog/mailhog
    container_name: symfony_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  adminer:
    image: adminer
    container_name: symfony_adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  mysql_data:

secrets:
  mysql_root_password:
    file: ./docker/mysql/root_password.txt
